apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "{{ .Values.reload }}"
  name: {{ include "olx.fullname" . }}
  labels:
    {{- include "olx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "olx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "olx.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 100
        runAsGroup: 101
      serviceAccountName: {{ .Values.security.user }}
      automountServiceAccountToken: {{ .Values.security.token }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: INIT_DATE
              valueFrom:
                configMapKeyRef:
                  key: date
                  name: "{{ .Chart.Name }}-config"
            - name: CUSTOM_MESSAGE
              valueFrom:
                configMapKeyRef:
                  key: message
                  name: "{{ .Chart.Name }}-config"
            - name: VERSION
              value: {{ .Chart.Version }}
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP                  
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python"]
          args: ["olx.py"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mount }}
      initContainers:
        - name: install
          image: busybox:1.32.0
          command: ['sh', '-c', "echo 'Waiting for data...' | tee {{ .Values.volume.mount }}/slow.txt"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}          
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mount }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-volume"