{
 "title": "List Offers",
 "tags": [
  "olx",
  "mysql"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Region",
    "query": "select distinct state from offer;"
   },
   {
    "name": "Brand",
    "query": "select distinct brand from offer;"
   },
   {
    "name": "Model",
    "query": "select distinct model from offer;"
   },
   {
    "name": "Color",
    "query": "select distinct carColor from offer;"
   }
  ]
 },
 "panels": [
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(O.code)\nFROM\n  offer O\nINNER JOIN\n  url U ON O.code = U.code\nWHERE\n  O.state in ($Region)\nAND O.carColor in ($Color)\nAND O.brand in ($Brand)\nAND FROM_UNIXTIME(U.date) >= $__timeFrom()\nAND FROM_UNIXTIME(U.date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "AVERAGE ODOMETER",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  AVG(O.mileageFromOdometer)\nFROM \n  offer O\nINNER JOIN\n  url U ON O.code = U.code  \nWHERE\n  O.state in ($Region) \nAND O.carColor in ($Color)\nAND O.brand in ($Brand)\nAND FROM_UNIXTIME(U.date) >= $__timeFrom()\nAND FROM_UNIXTIME(U.date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "AVERAGE SCORE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(S.score)\nFROM \n  offer O\nINNER JOIN\n  score S ON O.code = S.code\nINNER JOIN\n  url U ON O.code = U.code  \nWHERE \n  O.state in ($Region)\nAND O.carColor in ($Color)\nAND O.brand in ($Brand)\nAND FROM_UNIXTIME(U.date) >= $__timeFrom()\nAND FROM_UNIXTIME(U.date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "AVERAGE PRICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  AVG(O.price)\nFROM \n  offer O\nINNER JOIN\n  url U ON O.code = U.code  \nWHERE\n  O.state in ($Region) \nAND O.carColor in ($Color)\nAND O.brand in ($Brand)\nAND FROM_UNIXTIME(U.date) >= $__timeFrom()\nAND FROM_UNIXTIME(U.date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "MIN PRICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  MIN(O.price)\nFROM \n  offer O\nINNER JOIN\n  url U ON O.code = U.code  \nWHERE\n  O.state in ($Region) \nAND O.carColor in ($Color)\nAND O.brand in ($Brand)\nAND FROM_UNIXTIME(U.date) >= $__timeFrom()\nAND FROM_UNIXTIME(U.date) <= $__timeTo()\n"
    }
   ]
  },
  {
   "title": "MAX PRICE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  MAX(O.price)\nFROM \n  offer O\nINNER JOIN\n  url U ON O.code = U.code  \nWHERE\n  O.state in ($Region) \nAND O.carColor in ($Color)\nAND O.brand in ($Brand)\nAND FROM_UNIXTIME(U.date) >= $__timeFrom()\nAND FROM_UNIXTIME(U.date) <= $__timeTo()"
    }
   ]
  },
  {
   "title": "Offer",
   "type": "table",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  FROM_UNIXTIME(U.date, '%d/%m/%Y %H:%i') as 'DATE & TIME',\n  U.url as URL,\n  O.name as NAME,\n  O.modelDate as YEAR,\n  O.price as PRICE,\n  S.score as SCORE,\n  O.numberOfDoors as DOORS,\n  O.mileageFromOdometer as ODOMETER,\n  O.vehicleTransmission as TRANSMISSION,\n  O.fuelType as FUEL,\n  O.carColor as COLOR\nFROM \n  offer O\nINNER JOIN score S ON O.code = S.code \nINNER JOIN url U ON O.code = U.code\nWHERE \n  O.state in ($Region)\nAND \n  O.carColor in ($Color)\nAND\n  O.brand in ($Brand)\nAND\n  O.model in ($Model)\nAND\n  FROM_UNIXTIME(U.date) >= $__timeFrom()\nAND\n  FROM_UNIXTIME(U.date) <= $__timeTo()\nORDER BY\n  U.date DESC;"
    }
   ]
  }
 ]
}