{
 "title": "Global Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PICTURES - Average",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(pictures) FROM offer;\n"
    }
   ]
  },
  {
   "title": "PICTURES - Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(id) FROM image;\n" }
   ]
  },
  {
   "title": "AVG EXECUTION - Found",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(found) FROM status;\n"
    }
   ]
  },
  {
   "title": "TELEGRAM - New",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1) FROM notification WHERE message like 'Novo%';\n"
    }
   ]
  },
  {
   "title": "LAST EXECUTION - Found",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT found FROM status ORDER BY id DESC LIMIT 1;\n"
    }
   ]
  },
  {
   "title": "EXECUTION - Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT MAX(total) FROM status;\n"
    }
   ]
  },
  {
   "title": "PICTURES - Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "rawSql": "SELECT SUM(size) FROM image;\n" }
   ]
  },
  {
   "title": "PICTURES - Unique",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT md5) FROM image;\n"
    }
   ]
  },
  {
   "title": "AVG EXECUTION - Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG('update') FROM status;\n"
    }
   ]
  },
  {
   "title": "TELEGRAM - Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1) FROM notification WHERE message like '%foi atualizado%';"
    }
   ]
  },
  {
   "title": "LAST EXECUTION - Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT S.update FROM status S ORDER BY id DESC LIMIT 1;\n"
    }
   ]
  },
  {
   "title": "EXECUTION - Date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT FROM_UNIXTIME(S.date) FROM status S ORDER BY id DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "PRICE - History",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT U.url as URL, COUNT(H.price) as 'UPDATE'\nFROM history H\nINNER JOIN url U ON U.code = H.code\nGROUP BY H.code\nORDER BY 2 DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "AVG EXECUTION - Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(duration) FROM status;\n"
    }
   ]
  },
  {
   "title": "LAST EXECUTION - Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT duration FROM status ORDER BY id DESC LIMIT 1;\n"
    }
   ]
  },
  {
   "title": "AVG EXECUTION - Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(rate) FROM status;\n"
    }
   ]
  },
  {
   "title": "LAST EXECUTION - Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT rate FROM status ORDER BY id DESC LIMIT 1;\n"
    }
   ]
  }
 ]
}