---

  - name: Configure sshd
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regex: "^(#)?{{item.key}}"
      line: "{{item.key}} {{item.value}}"
      state: present
    loop:
      - { key: "ClientAliveInterval", value: 1200 }
      - { key: "ClientAliveCountMax", value: 6 }
      - { key: "PrintLastLog", value: "no" }
      - { key: "Port", value: "{{ ssh_port }}" }
      - { key: "PermitRootLogin", value: "no" }
      - { key: "X11Forwarding", value: "yes" }
      - { key: "PermitEmptyPasswords", value: "no" }
      - { key: "PasswordAuthentication", value: "no" }      
    notify:
      - restart ssh

  - name: Install Fail2ban
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - fail2ban

  - name: Configure Fail2ban
    template:
      src: fail2ban.j2
      dest: /etc/fail2ban/jail.local
    notify:
      - restart fail2ban

  - name: Enable Fail2ban
    service:
      name: fail2ban
      state: started
      enabled: yes

  - name: Enable Firewall
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Configure Firewall
    firewalld:
      port: "{{ ssh_port }}/tcp"
      permanent: yes
      state: enabled
    notify:
      - restart firewalld