---

  - name: Create ~{{ olx_user }}/.ssh folder
    file:
      path: "~{{ olx_user }}/.ssh"
      state: directory
      owner: "{{ olx_user }}"
      group: "{{ olx_user }}"
      mode: 0700
    tags:
      - ssh

  - name: Upload Pub key
    copy:
      src: "{{ ssh_pubkey }}"
      dest: ~{{ olx_user }}/.ssh/authorized_keys
      owner: "{{ olx_user }}"
      group: "{{ olx_user }}"
      mode: 0700
    tags:
      - ssh

  - name: Configure sshd
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regex: "^(#)?{{item.key}}"
      line: "{{item.key}} {{item.value}}"
      state: present
    loop:
      - { key: "ClientAliveInterval", value: 1200 }
      - { key: "ClientAliveCountMax", value: 6 }
      - { key: "PrintLastLog", value: "no" }
      - { key: "Port", value: "{{ ssh_port }}" }
      - { key: "PermitRootLogin", value: "no" }
      - { key: "X11Forwarding", value: "yes" }
      - { key: "PermitEmptyPasswords", value: "no" }
      - { key: "PasswordAuthentication", value: "no" }      
    notify:
      - restart ssh
    tags:
      - ssh

  - name: SSH CentOS
    include_tasks: centos.yaml
    when: ansible_os_family == "RedHat"

  - name: SSH Ubuntu
    include_tasks: ubuntu.yaml
    when: ansible_os_family == "Debian"

  - name: Enable Fail2ban
    service:
      name: fail2ban
      state: started
      enabled: yes
    tags:
      - ssh