apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.configmap.app_id }}-data"
  labels:
    type: local
spec:
  storageClassName: "{{ .Values.volume.storage_class }}"
  capacity:
    storage: {{ .Values.volume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.volume.path }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.configmap.app_id }}-volume"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}