---

  - name: Enable EPEL
    yum:
      name: epel-release
      state: latest
    tags:
      - base
      - centos

  - name: Install basic packages
    yum:
      name:
        - git
        - htop
        - zip
        - wget
        - dos2unix
        - vim
        - lsof
        - net-tools
        - jq
        - python3
        - python3-pip
    tags:
      - base
      - centos

  - name: Update all packages
    yum:
      name: '*'
      state: latest
    tags:
      - base
      - centos
      - update