---

  - name: Base CentOS
    include_tasks: centos.yaml
    when: ansible_os_family == "RedHat"
    tags:
      - base

  - name: Base Ubuntu
    include_tasks: ubuntu.yaml
    when: ansible_os_family == "Debian"
    tags:
      - base

  - name: Set hostname
    hostname:
      name: "olx-car"
    tags:
      - base

  - name: Set timezone
    timezone:
      name: "{{ tz }}"
    tags:
      - base

  - name: Set PS1
    lineinfile:
      path: /etc/profile.d/olx.sh
      line: export PS1="(OLX) [\t] \u@\h:\w \\$ \[$(tput sgr0)\]"
      create: yes
      owner: root
      group: root
      mode: 0644
      validate: /bin/bash -n %s
    tags:
      - base

  - name: Create OLX user
    user:
      name: "{{ olx_user }}"
      comment: OLX car
      uid: 222
      shell: /bin/bash
      create_home: True
      home: "/home/{{ olx_user }}"
    register: created_user
    tags:
      - base

  - name: Create OLX password
    shell: /usr/bin/openssl rand -base64 32
    register: olx_pass
    when: created_user.changed
    tags:
      - base

  - name: Define OLX password
    shell: echo {{ olx_user }}:{{ olx_pass.stdout }} | chpasswd
    when: created_user.changed
    tags:
      - base

  - name: Details of {{ olx_user }}
    debug: msg="Password for {{ olx_user }} is {{ olx_pass.stdout }}"
    when: created_user.changed
    tags:
      - base