volume:
  path: /mnt/c/data
  storage_class: standard
configmap:
  daemon_interval: 10
  car_brand: gm-chevrolet
  car_model: opala
  car_title: opala
  car_date_begin: 1975
  car_date_end: 1980
  car_region: es
  telegram_enable: False
  telegram_bot_token: NA
  telegram_chat_id: NA
  score_year: 1979
  score_color: Preto
  score_door: 2
  score_fuel: Gasolina
  score_transmission: Manual
  score_price: 30000
  score_keyword: SS,6cc
  mysql_sync: False
  mysql_database: olx
  mysql_host: localhost
  mysql_port: 3306
  mysql_user: NA
  mysql_pass: NA
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi