name: Build and Push - Car module

on:
  push:
    branches: [ master ]
    paths:
    - 'car/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'car/**'

  workflow_dispatch:

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Release version
      run: |
        source car/config.env
        echo "TAG=${APP_VERSION}" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push relase
      uses: docker/build-push-action@v2
      with:
        file: car/Dockerfile
        context: car
        push: true
        tags: uknbr/olx-car:${{ env.TAG }}

    - name: Build and push latest
      uses: docker/build-push-action@v2
      with:
        file: ./car/Dockerfile
        context: car
        push: true
        tags: uknbr/olx-car:latest