name: Build and Push - Report module

on:
  push:
    branches: [ master ]
    paths:
    - 'report/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'report/**'

  workflow_dispatch:

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Release version
      run: |
        source config.env
        echo "TAG=${APP_VERSION}" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push relase
      uses: docker/build-push-action@v2
      with:
        dockerfile: ./report/Dockerfile
        push: true
        tags: uknbr/olx-report:${{ env.TAG }}

    - name: Build and push latest
      uses: docker/build-push-action@v2
      with:
        dockerfile: ./report/Dockerfile
        push: true
        tags: uknbr/olx-report:latest